name: Playwright Automation
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Permissions needed to write the report to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Added python-dotenv to fix the ImportError
        pip install pytest-playwright allure-pytest pytest-xdist python-dotenv
        playwright install --with-deps

    # - name: Run Smoke and API Tests
    #   # We use 'continue-on-error' so the report generates even if a test fails
    #   run: pytest -m "smoke or api" --alluredir=allure-results
    #   continue-on-error: true

    - name: Run All Tests
      # Removed the -m filter so it grabs all 11+ tests
      run: pytest --alluredir=allure-results --screenshot=only-on-failure
      continue-on-error: true

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history